---
- name: Configurar servidor Debian para aplicação crítica
  hosts: all
  become: yes

  vars:
    timezone: "UTC"
    allowed_ports:
      - 22

  tasks:
    # Atualizar e instalar ferramentas administrativas essenciais
    - name: Atualizar pacotes e instalar dependências
      apt:
        name:
          - curl
          - vim
          - htop
        state: present
        update_cache: yes

    # Configurar o fuso horário
    - name: Configurar o fuso horário para UTC
      timezone:
        name: "{{ timezone }}"

    # Habilitar o parâmetro net.ipv4.ip_forward
    - name: Habilitar net.ipv4.ip_forward no kernel
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    # Configurar e habilitar o firewall UFW
    - name: Instalar UFW
      apt:
        name: ufw
        state: present

    - name: Permitir tráfego SSH inicial pelas portas configuradas
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ allowed_ports }}"

    - name: Configurar o UFW para negar tudo por padrão
      command: ufw default deny incoming

    - name: Habilitar UFW
      ufw:
        state: enabled

    # Reiniciar serviços críticos
    - name: Reiniciar UFW
      service:
        name: ufw
        state: restarted
